class WordList(object):
    def __init__(self, short_name, description, easy=None, medium=None,
                 hard=None, impossible=None):
        self.word_list = {
            'easy': easy or [],
            'medium': medium or [],
            'hard': hard or [],
            'impossible': impossible or [],
        }
        self.description = description
        self.short_name = short_name

    def get_all_words(self):
        all_words = []
        for level in self.word_list:
            all_words += [word for word in self.word_list[level]]
        return all_words

    def get_words(self, level='easy'):
        return self.word_list[level]


WORDLISTS = {
    'sport_teams': WordList(
        short_name='Sports Teams',
        description='Sport teams across multiple sports',
        easy=[
            "Atlanta Braves",
            "New York Mets",
            "Philadelphia Phillies",
            "Chicago Cubs",
            "St. Louis Cardinals",
            "Los Angeles Dodgers",
            "San Francisco Giants",
            "Boston Red Sox",
            "New York Yankees",
            "Chicago White Sox",
            "Detroit Tigers",
            "Minnesota Twins",
            "Oakland Athletics",
            "Seattle Mariners",
            "Boston Celtics",
            "New York Knicks",
            "Philadelphia 76ers",
            "Chicago Bulls",
            "Miami Heat",
            "Utah Jazz",
            "Golden State Warriors",
            "Los Angeles Lakers",
            "Buffalo Bills",
            "Miami Dolphins",
            "New England Patriots",
            "New York Jets",
            "Pittsburgh Steelers",
            "Indianapolis Colts",
            "Jacksonville Jaguars",
            "Tennessee Titans",
            "Denver Broncos",
            "Kansas City Chiefs",
            "Las Vegas Raiders",
            "Dallas Cowboys",
            "New York Giants",
            "Chicago Bears",
            "Detroit Lions",
            "Green Bay Packers",
            "Minnesota Vikings",
            "Atlanta Falcons",
            "New Orleans Saints",
            "Los Angeles Rams",
            "San Francisco 49ers",
            "Seattle Seahawks",
            "New York Rangers",
            "Detroit Red Wings",
            "Toronto Maple Leafs",
        ],
        medium=[
            "Buffalo Sabres",
            "Miami Marlins",
            "Washington Nationals",
            "Milwaukee Brewers",
            "Los Angeles Clippers",
            "Boston Bruins",
            "Cincinnati Reds",
            "Pittsburgh Pirates",
            "Colorado Rockies",
            "San Diego Padres",
            "Baltimore Orioles",
            "San Antonio Spurs",
            "Phoenix Suns",
            "Houston Astros",
            "Toronto Blue Jays",
            "Baltimore Ravens",
            "Cincinnati Bengals",
            "Cleveland Browns",
            "Texas Rangers",
            "Portland Trail Blazers",
            "Los Angeles Chargers",
            "Cleveland Guardians",
            "Arizona Diamondbacks",
            "Orlando Magic",
            "Columbus Blue Jackets",
            "Denver Nuggets",
            "Minnesota Timberwolves",
            "Houston Rockets",
            "Brooklyn Nets",
            "Carolina Panthers",
            "Atlanta Hawks",
            "Charlotte Hornets",
            "Arizona Cardinals",
            "Tampa Bay Buccaneers",
            "Carolina Hurricanes",
            "Philadelphia Eagles",
            "New Jersey Devils",
            "Montreal Canadiens",
            "Ottawa Senators",
            "Tampa Bay Lightning",
            "Chicago Blackhawks",
            "Colorado Avalanche",
            "Dallas Stars",
            "Anaheim Ducks",
            "Calgary Flames",
            "Edmonton Oilers",
            "Los Angeles Kings",
            "San Jose Sharks",
            "Seattle Kraken",
            "Vancouver Canucks",
        ],
        hard=[
            "Detroit Pistons",
            "Washington Wizards",
            "Dallas Mavericks",
            "Toronto Raptors",
            "New Orleans Pelicans",
            "Cleveland Cavaliers",
            "Oklahoma City Thunder",
            "Sacramento Kings",
            "Milwaukee Bucks",
            "Minnesota Wild",
            "Houston Texans",
            "Florida Panthers",
            "Washington Commanders",
            "Nashville Predators",
            "Arizona Coyotes",
            "St. Louis Blues",
            "Philadelphia Flyers",
            "Pittsburgh Penguins",
            "Winnipeg Jets",
            "Washington Capitals",
            "Kansas City Royals",
        ],
        impossible=[
            "Indiana Pacers",
            "Memphis Grizzlies",
            "Vegas Golden Knights",
            "New York Islanders",
            "Los Angeles Angels",
            "Tampa Bay Rays",
        ],
    ),
    'famous_books': WordList(
        short_name='Famous Books',
        description='Famous books known by most people',
        easy=[],
        medium=[],
        hard=[],
        impossible=[],
    ),

    'locations': WordList(
        short_name='Locations',
        description="""
        Cities, states, Countries, and other geographic features throughout the
        world.
        """,
        easy=[
            'New York',
            'Los Angeles',
            'Chicago',
            'Houston',
            'Phoenix',
            'Dallas',
            'Indianapolis',
            'San Francisco',
            'Seattle',
            'Denver',
            'Nashville',
            'Boston',
            'Las Vegas',
            'Portland',
            'Detroit',
            'Baltimore',
            'Atlanta',
            'Miami',
            'New Orleans',
            'Rome',
            'Beijing',
            'London',
            'Tokyo',
            'Mexico City',
            'Mumbai',
            'Moscow',
            'Paris',
            'Toronto',
            'Barcelona',
            'Singapore',
            'Taj Mahal',
            'Statue of Liberty',
            'The Sphinx',
            'Great Wall of China',
            'Eiffel Tower',
            'Great Pyramid of Giza',
            'Sydney Opera House',
            'Stonehenge',
        ],
        medium=[
            'Albuquerque',
            'Jacksonville',
            'San Diego',
            'Cleveland',
            'Memphis',
            'Philadelphia',
            'Kansas City',
            'Rio de Janeiro',
            'Delhi',
            'Cairo',
            'Jakarta, Indonesia',
            'Wuhan, China',
            'Baghdad, Iraq',
            'Kremlin',
            'The Grand Canyon',
            'Mount Everest',
            'The Louvre'
        ],
        hard=[
            'Leaning Tower of Pisa',
            'Milwaukee',
            'Minneapolis',
            'Alexandria',
            'San Jose',
            'Osaka',
            'Silk Road',
            'Nagoya, Japan'
            'Ho Chi Minh City, Vietnam',
            'Alexandria, Egypt',
            'Easter Island',
            'Machu Picchu, Peru'
            'The Colloseum, Rome',
            'Niagara Falls',
            'Forbidden City, China',
            'Chichen Itza, Mexico',
            'Mount Kilimanjaro',
            'Mount Fuji',
        ],
        impossible=[
            'Kuala Lumpur, Malaysia',
            'The Acropolis, Athens'
        ],
    ),
    'base_game': WordList(
        short_name='Default',
        description='Curated manual word list',
        easy=[
            'clipboard',
            'sunflower',
            'cotton candy',
            'dagger',
            'game show',
            'meow',
            'sardine',
            'priest',
            'costume',
            'Kermit the frog',
            'wheel',
            'pearl',
            'electric razor',
            'seagull',
            'tooth',
            'sparrow',
            'JFK',
            'tea party',
            'wallet',
            'knife',
            'toothache',
            'curtain',
            'shopping cart',
            'orange juice',
            'throwing star',
            'envelope',
            'rat',
            'mustard',
            'coal',
            'scrunchie',
            'genie',
            'soup',
            'dentist',
            'lens cap',
            'ketchup',
            'bone',
            'sand',
            'angry',
            'archer',
            'balance beam',
            'ballet',
            'braces',
            'Brave',
            'bright',
            'cheers',
            'chimpanzee',
            'clown',
            'coffee',
            'cradle',
            'dinosaur',
            'disco',
            'dizzy',
            'drool',
            'ears',
            'Electric Slide',
            'excitement',
            'firefighter',
            'fishing',
            'flick',
            'gallop',
            'giggle',
            'golf',
            'halo',
            'hiccup',
            'horns',
            'hot dog',
            'hungry',
            'hurricane',
            'hurt',
            'ice skating',
            'karate',
            'ladder',
            'Lady and the Tramp',
            'light bulb',
            'limbo',
            'Macarena',
            'makeup',
            'marriage',
            'mash',
            'mime',
            'mirror',
            'monster',
            'motorcycle',
            'nightmare',
            'nosey',
            'overwhelmed',
            'pancakes',
            'penguin',
            'phone',
            'photographer',
            'piano',
            'pirate',
            'President',
            'reach',
            'read',
            'remote',
            'Riverdance',
            'rockstar',
            'rollercoaster',
            'sad',
            'shadow',
            'shoelaces',
            'shuffle',
            'sick',
            'singer',
            'skip',
            'slice',
            'Slip n’ slide',
            'slippery',
            'smear',
            'soccer',
            'spider',
            'spin',
            'stomp',
            'strong',
            'stubbed toe',
            'sword',
            'tap dance',
            'The Jungle Book',
            'The Princess and the Frog',
            'The Sword in the Stone',
            'trampoline',
            'waterfall',
            'wheelbarrow',
            'wiggle',
        ],
        medium=[
            'film',
            'carrier pigeon',
            'alley',
            'digit',
            'double',
            'sculpture',
            'dog food',
            'luck',
            'Black Forest',
            'forest fire',
            'Twix',
            'Cherry Coke',
            'Jughead',
            'poet',
            'Ethan Allen',
            'Stockholm Syndrome',
            'science',
            'couch potato',
            'hedge',
            'elephant ear',
            'comet',
            'freezer',
            'daffodil',
            'sting',
            'sculpture',
            'chicken feed',
            'lime',
            'pi',
            'pillar',
            'delta',
            'rudder',
            'car horn',
            'chocolate milk'
        ]
    ),
    'nouns': WordList(
        short_name='Nouns',
        description='All nouns all the time.',
        hard=[
            'account',
            'achiever',
            'acoustics',
            'action',
            'activity',
            'addition',
            'adjustment',
            'advertisement',
            'advice',
            'aftermath',
            'afternoon',
            'afterthought',
            'agreement',
            'airplane',
            'airport',
            'amount',
            'amusement',
            'animal',
            'answer',
            'apparatus',
            'apparel',
            'apples',
            'appliance',
            'approval',
            'argument',
            'arithmetic',
            'attack',
            'attempt',
            'attention',
            'attraction',
            'authority',
            'babies',
            'balance',
            'balloon',
            'banana',
            'baseball',
            'basket',
            'basketball',
            'battle',
            'bedroom',
            'beetle',
            'beggar',
            'beginner',
            'behavior',
            'belief',
            'believe',
            'birthday',
            'border',
            'bottle',
            'boundary',
            'branch',
            'breakfast',
            'breath',
            'bridge',
            'brother',
            'brothers',
            'bubble',
            'bucket',
            'building',
            'bushes',
            'business',
            'butter',
            'button',
            'cabbage',
            'cactus',
            'calculator',
            'calendar',
            'camera',
            'cannon',
            'canvas',
            'caption',
            'carpenter',
            'carriage',
            'cattle',
            'celery',
            'cellar',
            'cemetery',
            'chairs',
            'chance',
            'change',
            'channel',
            'cheese',
            'cherries',
            'cherry',
            'chicken',
            'chickens',
            'children',
            'church',
            'circle',
            'clocks',
            'clouds',
            'clover',
            'cobweb',
            'collar',
            'comfort',
            'committee',
            'company',
            'comparison',
            'competition',
            'condition',
            'connection',
            'control',
            'copper',
            'country',
            'cracker',
            'crayon',
            'creator',
            'creature',
            'credit',
            'current',
            'curtain',
            'cushion',
            'daughter',
            'decision',
            'degree',
            'design',
            'desire',
            'destruction',
            'detail',
            'development',
            'digestion',
            'dinner',
            'direction',
            'discovery',
            'discussion',
            'disease',
            'disgust',
            'distance',
            'distribution',
            'division',
            'doctor',
            'donkey',
            'downtown',
            'drawer',
            'driving',
            'earthquake',
            'education',
            'effect',
            'eggnog',
            'engine',
            'example',
            'exchange',
            'existence',
            'expansion',
            'experience',
            'expert',
            'fairies',
            'family',
            'farmer',
            'father',
            'father',
            'faucet',
            'feather',
            'feeling',
            'fiction',
            'finger',
            'finger',
            'fireman',
            'flavor',
            'flight',
            'flower',
            'flowers',
            'friction',
            'friend',
            'friends',
            'furniture',
            'galley',
            'garden',
            'giants',
            'giraffe',
            'goldfish',
            'good-bye',
            'government',
            'governor',
            'grandfather',
            'grandmother',
            'ground',
            'growth',
            'guitar',
            'haircut',
            'hammer',
            'harbor',
            'harmony',
            'health',
            'hearing',
            'history',
            'hobbies',
            'holiday',
            'horses',
            'hospital',
            'houses',
            'hydrant',
            'icicle',
            'impulse',
            'income',
            'increase',
            'industry',
            'insect',
            'instrument',
            'insurance',
            'interest',
            'invention',
            'island',
            'jellyfish',
            'journey',
            'kettle',
            'kitten',
            'kittens',
            'knowledge',
            'laborer',
            'ladybug',
            'language',
            'lawyer',
            'learning',
            'leather',
            'letter',
            'letters',
            'lettuce',
            'library',
            'liquid',
            'lizards',
            'locket',
            'lumber',
            'lunchroom',
            'machine',
            'mailbox',
            'manager',
            'marble',
            'market',
            'measure',
            'meeting',
            'memory',
            'middle',
            'minister',
            'minute',
            'mitten',
            'monkey',
            'morning',
            'mother',
            'motion',
            'mountain',
            'muscle',
            'nation',
            'needle',
            'notebook',
            'number',
            'oatmeal',
            'observation',
            'office',
            'operation',
            'opinion',
            'orange',
            'oranges',
            'organization',
            'ornament',
            'pancake',
            'parcel',
            'parent',
            'partner',
            'passenger',
            'payment',
            'pencil',
            'person',
            'pickle',
            'picture',
            'pizzas',
            'planes',
            'plantation',
            'plants',
            'plastic',
            'playground',
            'pleasure',
            'plough',
            'pocket',
            'poison',
            'police',
            'polish',
            'pollution',
            'popcorn',
            'porter',
            'position',
            'potato',
            'powder',
            'prison',
            'process',
            'produce',
            'profit',
            'property',
            'protest',
            'punishment',
            'purpose',
            'quarter',
            'quartz',
            'question',
            'quicksand',
            'quince',
            'quiver',
            'rabbit',
            'rabbits',
            'railway',
            'rainstorm',
            'reaction',
            'reading',
            'reason',
            'receipt',
            'recess',
            'record',
            'regret',
            'relation',
            'religion',
            'representative',
            'request',
            'respect',
            'reward',
            'rhythm',
            'riddle',
            'scarecrow',
            'school',
            'science',
            'scissors',
            'seashore',
            'secretary',
            'selection',
            'servant',
            'sidewalk',
            'silver',
            'sister',
            'sisters',
            'snails',
            'snakes',
            'sneeze',
            'society',
            'spiders',
            'sponge',
            'spring',
            'square',
            'squirrel',
            'statement',
            'station',
            'sticks',
            'stitch',
            'stocking',
            'stomach',
            'stranger',
            'stream',
            'street',
            'stretch',
            'string',
            'structure',
            'substance',
            'suggestion',
            'summer',
            'support',
            'surprise',
            'sweater',
            'system	',
            'teaching',
            'temper',
            'tendency',
            'territory',
            'texture',
            'theory',
            'things',
            'thought',
            'thread',
            'thrill',
            'throat',
            'throne',
            'thunder',
            'ticket',
            'tomatoes',
            'tongue',
            'toothbrush',
            'toothpaste',
            'trains',
            'transport',
            'treatment',
            'trouble',
            'trousers',
            'trucks',
            'turkey',
            'umbrella',
            'underwear',
            'vacation',
            'vegetable',
            'vessel',
            'visitor',
            'volcano',
            'volleyball',
            'voyage',
            'wealth',
            'weather',
            'weight',
            'whistle',
            'wilderness',
            'window',
            'winter',
            'wrench',
            'writer',
            'Writing',
            'Yak-shaving',
            'Yelling',
            'Yourself',
            'Zoology',
        ],
        easy=[
            'act',
            'actor',
            'air',
            'alarm',
            'anger',
            'angle',
            'ant',
            'ants',
            'apple',
            'arch',
            'arm',
            'army',
            'art',
            'aunt',
            'baby',
            'back',
            'badge',
            'bag',
            'bait',
            'ball',
            'balls',
            'band',
            'base',
            'basin',
            'bat',
            'bath',
            'bead',
            'beam',
            'bean',
            'bear',
            'bears',
            'beast',
            'bed',
            'beds',
            'bee',
            'beef',
            'bell',
            'bells',
            'berry',
            'bike',
            'bikes',
            'bird',
            'birds',
            'birth',
            'bit',
            'bite',
            'blade',
            'blood',
            'blow',
            'board',
            'boat',
            'boats',
            'body',
            'bomb',
            'bone',
            'book',
            'books',
            'boot',
            'box',
            'boy',
            'boys',
            'brain',
            'brake',
            'brass',
            'bread',
            'brick',
            'brush',
            'bun',
            'burn',
            'burst',
            'cable',
            'cake',
            'cakes',
            'camp',
            'can',
            'cap',
            'car',
            'card',
            'care',
            'cars',
            'cart',
            'cast',
            'cat',
            'cats',
            'cause',
            'cave',
            'cent',
            'chain',
            'chair',
            'chalk',
            'chess',
            'chin',
            'clam',
            'class',
            'clock',
            'cloth',
            'cloud',
            'club',
            'coach',
            'coal',
            'coast',
            'coat',
            'coil',
            'color',
            'comb',
            'cook',
            'copy',
            'cord',
            'cork',
            'corn',
            'cough',
            'cover',
            'cow',
            'cows',
            'crack',
            'crate',
            'cream',
            'crib',
            'crime',
            'crook',
            'crow',
            'crowd',
            'crown',
            'crush',
            'cry',
            'cub',
            'cup',
            'curve',
            'dad',
            'day',
            'death',
            'debt',
            'deer',
            'desk',
            'dime',
            'dirt',
            'dock',
            'dog',
            'dogs',
            'doll',
            'dolls',
            'door',
            'drain',
            'dress',
            'drink',
            'drop',
            'drug',
            'drum',
            'duck',
            'ducks',
            'dust',
            'ear',
            'earth',
            'edge',
            'egg',
            'eggs',
            'elbow',
            'end',
            'error',
            'event',
            'eye',
            'eyes',
            'face',
            'fact',
            'fall',
            'fan',
            'fang',
            'farm',
            'fear',
            'feast',
            'feet',
            'field',
            'fifth',
            'fight',
            'fire',
            'fish',
            'flag',
            'flame',
            'flesh',
            'flock',
            'floor',
            'fly',
            'fog',
            'fold',
            'food',
            'foot',
            'force',
            'fork',
            'form',
            'fowl',
            'frame',
            'frog',
            'frogs',
            'front',
            'fruit',
            'fuel',
            'game',
            'gate',
            'geese',
            'ghost',
            'girl',
            'girls',
            'glass',
            'glove',
            'glue',
            'goat',
            'gold',
            'goose',
            'grade',
            'grain',
            'grape',
            'grass',
            'grip',
            'group',
            'guide',
            'gun',
            'hair',
            'hall',
            'hand',
            'hands',
            'hat',
            'hate',
            'head',
            'heart',
            'heat',
            'help',
            'hen',
            'hill',
            'hole',
            'home',
            'honey',
            'hook',
            'hope',
            'horn',
            'horse',
            'hose',
            'hot',
            'hour',
            'house',
            'humor',
            'ice',
            'idea',
            'ink',
            'iron',
            'jail',
            'jam',
            'jar',
            'jeans',
            'jelly',
            'jewel',
            'join',
            'joke',
            'judge',
            'juice',
            'jump',
            'key',
            'kick',
            'kiss',
            'kite',
            'kitty',
            'knee',
            'knife',
            'knot',
            'lace',
            'lake',
            'lamp',
            'land',
            'laugh',
            'lead',
            'leaf',
            'leg',
            'legs',
            'level',
            'lift',
            'light',
            'limit',
            'line',
            'linen',
            'lip',
            'list',
            'loaf',
            'lock',
            'look',
            'loss',
            'love',
            'low',
            'lunch',
            'magic',
            'maid',
            'man',
            'map',
            'mark',
            'mask',
            'mass',
            'match',
            'meal',
            'meat',
            'men',
            'metal',
            'mice',
            'milk',
            'mind',
            'mine',
            'mint',
            'mist',
            'mom',
            'money',
            'month',
            'moon',
            'mouth',
            'move',
            'music',
            'nail',
            'name',
            'neck',
            'need',
            'nerve',
            'nest',
            'net',
            'news',
            'night',
            'noise',
            'north',
            'nose',
            'note',
            'nut',
            'ocean',
            'offer',
            'oil',
            'order',
            'oven',
            'owl',
            'owner',
            'page',
            'pail',
            'pain',
            'paint',
            'pan',
            'paper',
            'park',
            'part',
            'party',
            'paste',
            'patch',
            'peace',
            'pear',
            'pen',
            'pest',
            'pet',
            'pets',
            'pie',
            'pies',
            'pig',
            'pigs',
            'pin',
            'pipe',
            'place',
            'plane',
            'plant',
            'plate',
            'play',
            'plot',
            'point',
            'pot',
            'power',
            'price',
            'print',
            'prose',
            'pull',
            'pump',
            'push',
            'queen',
            'quiet',
            'quill',
            'quilt',
            'rail',
            'rain',
            'rake',
            'range',
            'rat',
            'rate',
            'ray',
            'rest',
            'rice',
            'rifle',
            'ring',
            'rings',
            'river',
            'road',
            'robin',
            'rock',
            'rod',
            'roll',
            'roof',
            'room',
            'root',
            'rose',
            'route',
            'rub',
            'rule',
            'run',
            'sack',
            'sail',
            'salt',
            'sand',
            'scale',
            'scarf',
            'scene',
            'scent',
            'screw',
            'sea',
            'seat',
            'seed',
            'self',
            'sense',
            'shade',
            'shake',
            'shame',
            'shape',
            'sheep',
            'sheet',
            'shelf',
            'ship',
            'shirt',
            'shock',
            'shoe',
            'shoes',
            'shop',
            'show',
            'side',
            'sign',
            'silk',
            'sink',
            'size',
            'skate',
            'skin',
            'skirt',
            'sky',
            'slave',
            'sleep',
            'sleet',
            'slip',
            'slope',
            'smash',
            'smell',
            'smile',
            'smoke',
            'snail',
            'snake',
            'snow',
            'soap',
            'sock',
            'soda',
            'sofa',
            'son',
            'song',
            'songs',
            'sort',
            'sound',
            'soup',
            'space',
            'spade',
            'spark',
            'spoon',
            'spot',
            'spy',
            'stage',
            'stamp',
            'star',
            'start',
            'steam',
            'steel',
            'stem',
            'step',
            'stew',
            'stick',
            'stone',
            'stop',
            'store',
            'story',
            'stove',
            'straw',
            'sugar',
            'suit',
            'sun',
            'swim',
            'swing',
            'table',
            'tail',
            'talk',
            'tank',
            'taste',
            'tax',
            'team',
            'teeth',
            'tent',
            'test',
            'thing',
            'thumb',
            'tiger',
            'time',
            'tin',
            'title',
            'toad',
            'toe',
            'toes',
            'tooth',
            'top',
            'touch',
            'town',
            'toy',
            'toys',
            'trade',
            'trail',
            'train',
            'tray',
            'tree',
            'trees',
            'trick',
            'trip',
            'truck',
            'tub',
            'turn',
            'twig',
            'twist',
            'uncle',
            'unit',
            'use',
            'value',
            'van',
            'vase',
            'veil',
            'vein',
            'verse',
            'vest',
            'view',
            'voice',
            'walk',
            'wall',
            'war',
            'wash',
            'waste',
            'watch',
            'water',
            'wave',
            'waves',
            'wax',
            'way',
            'week',
            'wheel',
            'whip',
            'wind',
            'wine',
            'wing',
            'wire',
            'wish',
            'woman',
            'women',
            'wool',
            'worm',
            'wound',
            'wrist',
        ],
    ),
    'space': WordList(
        short_name='Space',
        description='Space-related words',
        easy=[
            'Apollo',
            'Moon',
            'Sun',
            'Venus',
            'Pluto',
            'Mars',
            'Earth',
            'Mercury',
            'Jupiter',
            'Saturn',
            'Uranus',
            'Neptune',
            'Planet',
            'Space',
            'Star'
        ],
        medium=[
            'Alien',
            'Alpha Centauri',
            'Asteroid',
            'Astronaut',
            'Astronomy',
            'Big Bang Theory',
            'Black Hole',
            'Buzz Aldrin',
            'Ceres',
            'Comet',
            'Constellation',
            'Cosmonaut',
            'Crater',
            'Curiosity Rover',
            'Eclipse',
            'Event Horizon',
            'Galaxy',
            'Gas Giant',
            'Gravity',
            'Hubble Telescope',
            'International Space Station',
            'Laika (First dog in space)',
            'Lightyear',
            'Meteor',
            'Milky Way',
            'Mercury',
            'NASA',
            'Nebula',
            'Neil Armstrong',
            'Orbit',
            'Parsec',
            'Pulsar',
            'Quasar',
            'Red Dwarf',
            'Red Giant',
            'Red Shift',
            'Rocket',
            'Satellite',
            'Solar Flare',
            'Solar System',
            'Sputnik',
            'Supernova',
            'Telescope',
            'Titan',
            'Universe',
            'White Dwarf',
            'Wormhole',
            'Yellow Dwarf',
            'Vacuum'
        ]),
    'extended': WordList(
        short_name='extended',
        description='Auto-generated Word List',
        easy=[
            'actor',
            'adult',
            'airplane',
            'alarm clock',
            'alive',
            'ankle',
            'apple',
            'awake',
            'baby',
            'backpack',
            'bald',
            'balloon',
            'banana',
            'bark',
            'baseball',
            'basketball',
            'bat',
            'bathroom',
            'beach',
            'beak',
            'bed',
            'bedtime',
            'below',
            'bench',
            'big',
            'black',
            'blanket',
            'blind',
            'blue jeans',
            'boat',
            'book',
            'bounce',
            'bowl',
            'boy',
            'bracelet',
            'brake',
            'branch',
            'broccoli',
            'broken',
            'broom',
            'brother',
            'bug',
            'bumblebee',
            'butterfly',
            'button',
            'buy',
            'calculator',
            'camera',
            'car',
            'chair',
            'cheek',
            'chocolate',
            'Christmas',
            'circle',
            'city',
            'clap',
            'classroom',
            'clean',
            'cold',
            'comb',
            'corn',
            'count',
            'cousin',
            'crack',
            'crib',
            'cube',
            'cup',
            'cupcake',
            'curl',
            'dad',
            'dance',
            'deep',
            'diamond',
            'dirt',
            'dog',
            'door',
            'dream',
            'drum',
            'duck',
            'egg',
            'elephant',
            'envelope',
            'exercise',
            'eye',
            'fact',
            'fall',
            'family',
            'farm',
            'feet',
            'fire',
            'first',
            'fish',
            'flashlight',
            'flower',
            'fly',
            'football',
            'forehead',
            'fork',
            'fountain',
            'frog',
            'frown',
            'frying pan',
            'full',
            'fur',
            'gift',
            'giraffe',
            'glasses',
            'grape',
            'gum',
            'gym',
            'hair',
            'half',
            'hamburger',
            'hand',
            'happy',
            'heavy',
            'helicopter',
            'help',
            'hit',
            'homework',
            'hook',
            'horse',
            'hotel',
            'house',
            'ice cream cone',
            'Internet',
            'iron',
            'jacket',
            'jail',
            'jar',
            'jellyfish',
            'juice',
            'king',
            'kite',
            'lamp',
            'leaf',
            'legs',
            'lightning',
            'line',
            'lion',
            'lizard',
            'long',
            'loud',
            'love',
            'low',
            'lunchbox',
            'lung',
            'mailbox',
            'mailman',
            'MC Hammer',
            'melt',
            'Mickey Mouse',
            'milk',
            'mitten',
            'moo',
            'moon',
            'mountains',
            'mouth',
            'music',
            'nail polish',
            'neighbor',
            'nest',
            'nice',
            'notebook',
            'old',
            'owl',
            'pantry',
            'party',
            'pencil',
            'person',
            'picture',
            'pig',
            'pillow',
            'play',
            'policeman',
            'popsicle',
            'purple',
            'purse',
            'quiet',
            'rainbow',
            'ranch',
            'refrigerator',
            'restaurant',
            'rhyme',
            'ride',
            'river',
            'road',
            'rock',
            'rocket',
            'roof',
            'room',
            'run',
            'school bus',
            'scientist',
            'sea turtle',
            'sea',
            'seashell',
            'share',
            'shark',
            'ship',
            'shoe',
            'shopping',
            'shower',
            'sink',
            'Sir Mix-A-Lot',
            'skateboard',
            'sleep',
            'smell',
            'smile',
            'snail',
            'snake',
            'soap',
            'sock',
            'socks',
            'square',
            'stamp',
            'stapler',
            'star',
            'stick',
            'stomach',
            'stream',
            'street',
            'study',
            'suitcase',
            'sun',
            'swimming pool',
            'swing',
            'table',
            'tail',
            'tent',
            'thunder',
            'tissue',
            'touchdown',
            'towel',
            'tractor',
            'train',
            'tree',
            'trip',
            'truck',
            'turtle',
            'TV',
            'umbrella',
            'vacation',
            'Vanilla Ice',
            'waitress',
            'watch',
            'wave',
            'wind',
            'wrinkle',
            'yellow',
            'yo-yo',
            'zero',
            'zigzag',
        ],
        medium=[
            'acne',
            'attic',
            'baby-sitter',
            'bait',
            'banister',
            'baseboards',
            'bass',
            'birthday',
            'bite',
            'blanket',
            'blossom',
            'bobsled',
            'boil',
            'bonnet',
            'brass',
            'brick',
            'bubble',
            'budget',
            'bump',
            'bunk bed',
            'button',
            'cage',
            'calorie',
            'camp',
            'campsite',
            'candlestick',
            'career',
            'caribou',
            'cartographer',
            'cartoon',
            'cell',
            'chauffeur',
            'church',
            'classroom',
            'cloud',
            'coupon',
            'crumb',
            'curb',
            'currency',
            'curtains',
            'date',
            'decide',
            'delay',
            'departure',
            'dirt',
            'dragonfly',
            'drums',
            'earache',
            'easel',
            'elf',
            'envious',
            'experiment',
            'face',
            'family reunion',
            'fine',
            'friend',
            'gasoline',
            'glue stick',
            'goblin',
            'gold',
            'gumball',
            'healthy',
            'heel',
            'hide-and-seek',
            'hike',
            'hip',
            'hoedown',
            'hook',
            'hotel',
            'hug',
            'hurdle',
            'infant',
            'ironing board',
            'jog',
            'joyful',
            'judgmental',
            'knight',
            'lamp',
            'leak',
            'leotard',
            'linen',
            'lip',
            'log',
            'lunch tray',
            'magnet',
            'map',
            'mast',
            'matchstick',
            'mold',
            'mom',
            'mop',
            'motel',
            'mountain biking',
            'mountain',
            'nail',
            'net',
            'Nirvana',
            'nitrogen',
            'oak tree',
            'observe',
            'operation',
            'order',
            'park',
            'pharmacy',
            'photograph',
            'ping pong',
            'plane',
            'pogo stick',
            'porch swing',
            'poster',
            'predator',
            'pride',
            'produce',
            'puppet',
            'quicksand',
            'quill',
            'race',
            'railroad',
            'rake',
            'rattle',
            'rebound',
            'recycle',
            'reign',
            'ribbon',
            'rind',
            'road trip',
            'robin',
            'rug',
            'rut',
            'safari',
            'sandpaper',
            'seesaw',
            'senior',
            'sense',
            'sentence',
            'shack',
            'shed',
            'sheet',
            'shrimp',
            'sideline',
            'silver',
            'silverware',
            'sin',
            'skull',
            'slam dunk',
            'slide',
            'smog',
            'smoke',
            'snack',
            'snowball',
            'sod',
            'soil',
            'son',
            'spaceship',
            'spouse',
            'spring',
            'spy',
            'squint',
            'stage',
            'stairs',
            'state',
            'stationery',
            'steel',
            'stepmom',
            'stream',
            'stripe',
            'sun block',
            'sunshine',
            'swing',
            'tailor',
            'tank',
            'taxi',
            'teammate',
            'teenager',
            'think',
            'thread',
            'tiptoe',
            'toad',
            'toddler',
            'tool',
            'top hat',
            'trailer',
            'transport',
            'trash can',
            'tulip',
            'twig',
            'usher',
            'veil',
            'vent',
            'waist',
            'wallet',
            'waste',
            'waves',
            'weed',
            'wick',
            'Windex',
            'word',
            'writer',
            'x-ray',
            'yam',
        ],
        hard=[
            'abrasive',
            'actuary',
            'admit',
            'agenda',
            'airway',
            'altitude',
            'amateur',
            'application',
            'audacity',
            'ballpoint pen',
            'banana peel',
            'baron',
            'battle',
            'bay',
            'bedbug',
            'beehive',
            'bellhop',
            'blimp',
            'blur',
            'bonnet',
            'brand',
            'brass',
            'breakdance',
            'bucket',
            'campsite',
            'capitalism',
            'capybara',
            'chain',
            'chicken coop',
            'clay',
            'cloak',
            'coast',
            'confused',
            'crime',
            'crop',
            "crows nest",
            'cuff',
            'cupola',
            'cure',
            'dawn',
            'degree',
            'demo',
            'deployed',
            'dimple',
            'diver',
            'divine',
            'dress shirt',
            'dust bunny',
            'ebony and ivory',
            'eternity',
            'example',
            'exhort',
            'fabric',
            'feudalism',
            'fizz',
            'flu',
            'flush',
            'forever',
            'fortnight',
            'fourth down',
            'freight train',
            'fringe',
            'full moon',
            'Galapagos tortoise',
            'game clock',
            'garden hose',
            'gem',
            'genetics',
            'glum',
            'gray hairs',
            'group',
            'gusto',
            'hardhearted',
            'hatch',
            'help',
            'highjack',
            'highway',
            'hole in one',
            'humidifier',
            'image',
            'immune',
            'incident',
            'insist',
            'intern',
            'irritated',
            'jade',
            'jazz',
            'jog',
            'jug',
            'jury',
            'kiosk',
            'ladder rung',
            'laundry basket',
            'lecture',
            'leisure',
            'livestock',
            'lollipop',
            'major league',
            'mascot',
            'mast',
            'maze',
            'midsummer',
            'modern',
            'moped',
            'motion',
            'multiplication',
            "Murphys Law",
            'nanny',
            'nutrient',
            'oak tree',
            'observation',
            'organ',
            'outlet mall',
            'overhang',
            'password',
            'path',
            'payment',
            'perk',
            'person',
            'phonemics',
            'pinch',
            'pint',
            'plank',
            'plug',
            'pomp',
            'population',
            'porch swing',
            'position',
            'potassium',
            'premolar',
            'process',
            'program',
            'publisher',
            'purpose',
            'puzzle piece',
            'quality control',
            'quantum mechanics',
            'race',
            'radiation',
            'radiator',
            'range',
            'rendering',
            'research',
            'result',
            'rhetoric',
            'riddle',
            'romance',
            'runt',
            'rut',
            'safe',
            'sandbox',
            'sash',
            'scanner',
            'scar tissue',
            'scenery',
            'scoundrel',
            'scramble',
            'scuff mark',
            'scurvy',
            'scythe',
            'selection',
            'self',
            'sentence',
            'serve',
            'sheriff',
            'shipwreck',
            'shriek',
            'shrink ray',
            'sip',
            'sling',
            'smidgen',
            'snag',
            'snobbish',
            'snort',
            'snow shoe',
            'sod',
            'someone',
            'speakers',
            'speculate',
            'spoonful',
            'sports car',
            'standard',
            'standing ovation',
            'state fair',
            'station',
            'station wagon',
            'statistics',
            'step-daughter',
            'stipulate',
            'stockbroker',
            'structure',
            'suggestion',
            'sum',
            'sunglasses',
            'suspend',
            'sympathize',
            'tendency',
            'theorize',
            'thing',
            'thoughtless',
            'throb',
            'tine',
            'toboggan',
            'traffic jam',
            'train station',
            'tugboat',
            'tunic',
            'turnpike',
            'twitterpated',
            'underestimate',
            'urgent',
            'use',
            'voice',
            'wail',
            'waver',
            'way',
            'whole milk',
            'wish',
            'wreath',
            'zephyr',
            'Moe Shop',
        ]),
    'movies': WordList(
        short_name='Movies',
        description='Movies',
        medium=[
            "12 Angry Men",
            "2001: A Space Odyssey",
            "A Beautiful Mind",
            "A Clockwork Orange",
            "Aladdin",
            "Aliens",
            "Amadeus",
            "American History X",
            "Apocalypse Now",
            "Avengers: Infinity War",
            "Back to the Future",
            "Batman Begins",
            "Before Sunrise",
            "Blade Runner",
            "Braveheart",
            "Casablanca",
            "Catch Me If You Can",
            "Citizen Kane",
            "Dead Poets Society",
            "Die Hard",
            "Django Unchained",
            "Eternal Sunshine of the Spotless Mind",
            "Fargo",
            "Fight Club",
            "Finding Nemo",
            "Forrest Gump",
            "Full Metal Jacket",
            "Gladiator",
            "Gone Girl",
            "Good Will Hunting",
            "Gran Torino",
            "Groundhog Day",
            "How to Train Your Dragon",
            "Howls Moving Castle",
            "Inception",
            "Indiana Jones and the Raiders of the Lost Ark",
            "Inglourious Basterds",
            "Inside Out",
            "Interstellar",
            "Its a Wonderful Life",
            "Jaws",
            "Joker",
            "Judgment at Nuremberg",
            "Jurassic Park",
            "Kill Bill: Vol. 1",
            "Léon: The Professional",
            "Life of Brian",
            "Mad Max: Fury Road",
            "Memento",
            "Monsters, Inc.",
            "Monty Python and the Holy Grail",
            "My Neighbor Totoro",
            "No Country for Old Men",
            "One Flew Over the Cuckoos Nest",
            "Pans Labyrinth",
            "Pirates of the Caribbean: The Curse of the Black Pearl",
            "Platoon",
            "Princess Mononoke",
            "Psycho",
            "Pulp Fiction",
            "Raging Bull",
            "Ratatouille",
            "Requiem for a Dream",
            "Reservoir Dogs",
            "Rocky",
            "Saving Private Ryan",
            "Scarface",
            "Schindlers List",
            "Shutter Island",
            "Spider-Man: Into the Spider-Verse",
            "Spirited Away",
            "Stand by Me",
            "Star Wars",
            "Taxi Driver",
            "Terminator 2: Judgment Day",
            "The Apartment",
            "The Big Lebowski",
            "The Dark Knight",
            "The Departed",
            "The Green Mile",
            "The Hunt",
            "The Incredibles",
            "The Iron Giant",
            "The Lion King",
            "The Lord of the Rings: The Fellowship of the Ring",
            "The Matrix",
            "The Pianist",
            "The Prestige",
            "The Shawshank Redemption",
            "The Shining",
            "The Silence of the Lambs",
            "The Sixth Sense",
            "The Sound of Music",
            "The Terminator",
            "The Usual Suspects",
            "The Wizard of Oz",
            "There Will Be Blood",
            "To Kill a Mockingbird",
            "Top Gun: Maverick",
            "Toy Story",
            "Trainspotting",
            "V for Vendetta",
            "WALL·E",
        ]),
    'movie_characters': WordList(
        short_name='Movie Characters',
        description='Character names from Movies',
        medium=[
            'Donatello',
            'Michelangelo',
            'Raphael',
            'Leonardo',
            'Ace Ventura',
            'Achilles',
            'Agent Smith',
            'Aladdin',
            'Anton Chigurh',
            'Aragorn',
            'Atreyu',
            'Atticus Finch',
            'Aurora',
            'Bagheera',
            'Baloo',
            'Bambi',
            'Bane',
            'Bastian Balthazar Bux',
            'Batman',
            'BeetleJuice',
            'Biff Tannen',
            'Bilbo Baggins',
            'Boba Fett',
            'Buffalo Bill',
            'Buzz Lightyear',
            'Captain America',
            'Captain Hook',
            'Captain Jack Sparrow',
            'Captain Kirk',
            'Casper',
            'Catwoman',
            'Chesire Cat',
            'Chief Brody',
            'Christopher Robin',
            'Chucky',
            'Chunk (Goonies)',
            'Cinderella',
            'Clarice Starling',
            'Cleopatra',
            'Cogsworth',
            'Col. Nathan R. Jessep',
            'Commodus',
            'Conan the Barbarian',
            'Cruella De Vil',
            'Daniel LaRusso',
            'Darth Maul',
            'Darth Vader',
            'Data (Goonies)',
            'Davy Jones',
            'Dennis the Menace',
            'Django',
            'Doc Brown',
            'Doc Holiday',
            'Donald Duck',
            'Dopey',
            'Dorothy Gale',
            'Dr. Evil',
            'Dr. King Schultz',
            'Dr. Otto Octavius',
            'Dracula',
            'Dredd',
            'Dudley Do-Right',
            'Dumbo',
            'E.T.',
            'Ebenezer Scrooge',
            'Edward Scissor Hands',
            'Elizabeth Swann',
            'Ellen Ripley',
            'Elliot Ness',
            'Elsa (Frozen)',
            'Ethan Hunt',
            'Fairy Godmother',
            'Falkor',
            'Ferris Bueller',
            'Frank Drebin',
            'Freddy Krueger',
            'Frodo',
            'Galadriel',
            'Gandalf ',
            'George Bailey',
            'Gepetto',
            'Gimli',
            'Gmork',
            'Godzilla',
            'Gollum',
            'Goofy',
            'Groot',
            'Grumpy',
            'Hades',
            'Han Solo',
            'Hannibal Lector',
            'Hans Landa',
            'Harley Quinn',
            'Harry Crumb',
            'Harry Potter',
            'Headless Horseman',
            'Hercules',
            'Hermione Granger',
            'Ichabod',
            'Imperator Furiosa',
            'Indiana Jones',
            'Inigo Montoya',
            'Iron Man',
            'Jabba the Hutt',
            'Jack and the Beanstalk',
            'Jack Burton',
            'Jack Skellington',
            'Jafar',
            'James Bond',
            'Jason Bourne',
            'Jason Voorhees',
            'Jaws',
            'Jessica Rabbit',
            'Jiminy Cricket',
            'John McClane',
            'John Rambo',
            'John Wick',
            'Joker',
            'Jules Winnfield',
            'Katniss Everdeen',
            'Kevin McCallister',
            'Khan',
            'King Kong',
            'King Triton',
            'Kronk',
            'Kuzco',
            'Lara Croft',
            'Legolas',
            'Leia Organa',
            'Lex Luthor ',
            'Little John',
            'Luke Skywalker',
            'Lumiere',
            'Mad Max',
            'Magic Carpet',
            'Maleficent',
            'Marge Gunderson',
            'Marion Ravenwood',
            'Martin Hooper',
            'Marty Mcfly',
            'Mary Poppins',
            'Matilda',
            'Maximus',
            'Michael Myers',
            'Mickey Mouse',
            'Mike Wazowski',
            'Minnie Mouse',
            'Miracle Max',
            'Mouth (Goonies)',
            'Mowgli',
            'Mr. Darcy',
            'Mr. Incredible',
            'Mr. Smee',
            'Mrs. Potts',
            'Mufasa',
            'Mulan',
            'Mushu',
            'Nemo ',
            'Neo',
            'Norman Bates',
            'Nurse Ratched',
            'Obi-Wan Kenobi',
            'Olaf',
            'Oogie Boogie Man',
            'Optimus Prime',
            'Oskar Schindler',
            'Palpatine',
            'PeeWee Herman',
            'Pennywise (IT)',
            'Peter Pan',
            'Peter Venkman',
            'Pikachu',
            'PinHead',
            'Pinocchio',
            'Pocahontas',
            'Popeye',
            'Predator',
            'Prince Humperdinck',
            'Prince Phillip',
            'Princess Fiona',
            'Professor Moriarty',
            'Pumbaa',
            'Quasimodo',
            'Queen of Hearts',
            'Quint',
            'Red (Shawshank Redemption)',
            'Rapunzel',
            'Rick Deckard',
            'Robin Hood',
            'Robocop',
            'Rockbiter',
            'Rocky Balboa',
            'Roger Rabbit',
            'Ron Weasley',
            'Rose (Titanic)',
            'Samwise Gamgee',
            'Santa',
            'Sarah Conner',
            'Sauron',
            'Shere Khan',
            'Sheriff Woody',
            'Sherlock Holmes',
            'Shredder',
            'Shrek',
            'Simba',
            'Sloth (Goonies)',
            'Smaug',
            'Snake Plissken',
            'Snow White',
            'Spider-Man',
            'Spock',
            'Superman',
            'Sweeney Todd',
            'Tarzan',
            'Terminator',
            'Thanos',
            'The Dude',
            'The Genie',
            'The Grinch',
            'The Hulk',
            'The Kracken',
            'The Mad Hatter',
            'The Mask',
            'The White Witch',
            'Thor',
            'Tigger',
            'Tinker Belle',
            'Tommy DeVito',
            'Tony Montana',
            'Uncle Buck',
            'Ursela',
            'Vito Corleone',
            'Walter Sobchak',
            'Wednesday Addams',
            'Wicked Witch of the West',
            'William Wallace',
            'Willy Wonka',
            'Winnie the Pooh',
            'Wolverine',
            'Wonder Woman',
            'Wyatt Earp',
            'Yoda',
            'Zeus',
            'Zorro',
        ]),
    'actors': WordList(
        short_name='Actors/Actresses',
        description='Actors and Actresses from Movies',
        medium=[
            'Chris Evans',
            'Robert Downey Jr.',
            'Jennifer Lawrence',
            'Channing Tatum',
            'George Clooney',
            'Johnny Depp',
            'Margot Robbie',
            'Jared Leto',
            'Ryan Reynolds',
            'Ryan Gosling',
            'Scarlett Johansson',
            'Brad Pitt',
            'Matt Damon',
            'Will Smith',
            'Ben Affleck',
            'Matthew McConaughey',
            'Chris Hemsworth',
            'Dwayne Johnson',
            'Tom Hiddleston',
            'Jamie Foxx',
            'Nicolas Cage',
            'Tom Cruise',
            'Chris Pratt',
            'Samuel L. Jackson',
            'Leonardo DiCaprio',
            'Tyler Perry',
            'Gal Gadot',
            'Idris Elba',
            'Tom Hanks',
            'Cara Delevingne',
            'Will Ferrell',
            'Ben Stiller',
            'Melissa McCarthy',
            'Vin Diesel',
            'Charlize Theron',
            'Anna Kendrick',
            'Bradley Cooper',
            'Amy Poehler',
            'Mark Wahlberg',
            'Daisy Ridley',
            'Jessica Chastain',
            'Kristen Wiig',
            'James McAvoy',
            'Denzel Washington',
            'Felicity Jones', ]),
    'games': WordList(
        short_name='Board and Video Games',
        description='Board and Video Games',
        medium=[
            'Baldurs Gate 3',
            'Batman: Arkham City',
            'BioShock',
            'BioShock Infinite',
            'Call of Duty 4: Modern Warfare',
            'Call of Duty: Modern Warfare 2',
            'Celeste',
            'Chrono Cross',
            'Devil May Cry',
            'Disco Elysium',
            'Elden Ring',
            'Final Fantasy',
            'Gears of War',
            'God of War',
            'GoldenEye 007',
            'Grand Theft Auto V',
            'Gran Turismo',
            'Half-Life 2',
            'Halo: Combat Evolved',
            'LittleBigPlanet',
            'Mass Effect 2',
            'Metal Gear Solid V: The Phantom Pain',
            'Metroid Prime',
            'Perfect Dark',
            'Persona 5 Royal',
            'Portal 2',
            'Quake',
            'Red Dead Redemption 2',
            'Resident Evil 4',
            'Sid Meiers Civilization II',
            'SoulCalibur',
            'Super Mario Galaxy',
            'Super Mario Odyssey',
            'Tekken 3',
            'The Elder Scrolls V: Skyrim',
            'The Last of Us',
            'The Legend of Zelda: A Link to the Past',
            'The Orange Box',
            'The Witcher 3: Wild Hunt - Complete Edition',
            'Tony Hawks Pro Skater 2',
            'Uncharted 2: Among Thieves',
            'World of Goo',
        ]),
}
