class WordList(object):
    def __init__(self, short_name, description, easy=None, medium=None,
                 hard=None, impossible=None):
        self.word_list = {
            'easy': easy or [],
            'medium': medium or [],
            'hard': hard or [],
            'impossible': impossible or [],
        }
        self.description = description
        self.short_name = short_name

    def get_all_words(self):
        all_words = []
        for level in self.word_list:
            all_words += [word for word in self.word_list[level]]
        return all_words

    def get_words(self, level='easy'):
        return self.word_list[level]


WORDLISTS = {
    'famous_books': WordList(
        short_name='Famous Books',
        description='Famous books known by most people',
        easy=[],
        medium=[],
        hard=[],
        impossible=[],
    ),
    'locations': WordList(
        short_name='Locations',
        description="""
        Cities, states, Countries, and other geographic features throughout the
        world.
        """,
        easy=[
            'New York',
            'Los Angeles',
            'Chicago',
            'Houston',
            'Phoenix',
            'Dallas',
            'San Francisco',
            'Seattle',
            'Denver',
            'Boston',
            'Las Vegas',
            'Portland',
            'Detroit',
            'Baltimore',
            'Atlanta',
            'Miami',
            'New Orleans',
            'Rome',
            'Beijing',
            'London',
            'Tokyo',
            'Moscow',
            'Paris',
            'The Sphinx',
            'Great Wall of China',
            'Eiffel Tower',
            'Great Pyramid of Giza',
            'Stonehenge',
        ],
        medium=[
            'The Grand Canyon',
            'Mount Everest',
            'The Louvre'
        ],
        hard=[
            'Leaning Tower of Pisa',
            'Mount Kilimanjaro',
            'Mount Fuji',
        ],
    ),
    'base_game': WordList(
        short_name='Default',
        description='Curated manual word list',
        easy=[
            'clipboard',
            'sunflower',
            'cotton candy',
            'dagger',
            'game show',
            'sardine',
            'priest',
            'costume',
            'Kermit the frog',
            'wheel',
            'pearl',
            'electric razor',
            'seagull',
            'tooth',
            'sparrow',
            'JFK',
            'tea party',
            'wallet',
            'knife',
            'toothache',
            'curtain',
            'shopping cart',
            'orange juice',
            'throwing star',
            'envelope',
            'rat',
            'mustard',
            'coal',
            'scrunchie',
            'genie',
            'soup',
            'dentist',
            'lens cap',
            'ketchup',
            'bone',
            'sand',
            'angry',
            'archer',
            'balance beam',
            'ballet',
            'braces',
            'Brave',
            'bright',
            'cheers',
            'chimpanzee',
            'clown',
            'coffee',
            'cradle',
            'dinosaur',
            'disco',
            'dizzy',
            'drool',
            'Electric Slide',
            'excitement',
            'firefighter',
            'fishing',
            'flick',
            'gallop',
            'giggle',
            'golf',
            'halo',
            'hiccup',
            'hot dog',
            'hungry',
            'hurricane',
            'hurt',
            'ice skating',
            'karate',
            'ladder',
            'Lady and the Tramp',
            'light bulb',
            'limbo',
            'Macarena',
            'makeup',
            'marriage',
            'mash',
            'mime',
            'mirror',
            'monster',
            'motorcycle',
            'nightmare',
            'nosey',
            'overwhelmed',
            'penguin',
            'phone',
            'photographer',
            'piano',
            'pirate',
            'President',
            'reach',
            'read',
            'remote',
            'Riverdance',
            'rockstar',
            'rollercoaster',
            'sad',
            'shadow',
            'shoelaces',
            'shuffle',
            'sick',
            'singer',
            'skip',
            'slice',
            'Slip n’ slide',
            'slippery',
            'smear',
            'soccer',
            'spider',
            'spin',
            'stomp',
            'strong',
            'sword',
            'tap dance',
            'The Princess and the Frog',
            'trampoline',
            'waterfall',
            'wheelbarrow',
        ],
        medium=[
            'apricot',
            'blue',
            'brown',
            'car horn',
            'comet',
            'daffodil',
            'digit',
            'dog food',
            'elephant ear',
            'Ethan Allen',
            'freezer',
            'meow',
            'green',
            'kitchen',
            'lime',
            'mouse',
            'patient',
            'pi',
            'pillar',
            'pink',
            'red',
            'rudder',
            'tablecloth',
            'telephone',
            'traffic',
            'The Jungle Book',
            'The Sword in the Stone',
            'Twix',
            'village',
            'white',
        ],
        hard=[
            'stubbed toe',
            'wiggle',
            'weapon',
            'million',
        ]

    ),
    'extended_game': WordList(
        short_name='Extended game words',
        description='Words not found in base, but generic additions.',
        easy=[
            'Albert Einstein',
            'Avocado',
            'Blender',
            'Dwayne "The Rock" Johnson',
            'Elvis Presley',
            'Freddie Mercury',
            'Jalapeno',
            'Mango',
        ],
        medium=[
            'Homer Simpson',
            'Apple pie',
            'Cantaloupe',
            'Cauliflower',
            'Chameleon',
            'Chopsticks',
            'Richard Nixon',
        ],
        hard=[
            'Amelia Earhart',
            'Antarctica',
            'Corn dog',
            'Cucumber',
            'Death Valley',
            'Disney World',
            'Flamingo',
            'Gandhi',
            'Genghis Khan',
            'Great Barrier Reef',
            'Hairbrush',
            'Hedgehog',
            'Hippopotamus',
            'Homer Simpson',
            'Hula hoop',
            'Jackie Chan',
            'Mariana Trench',
            'Mark Twain',
            'Martin Luther King Jr.',
            'Mt. Everest',
            'Napoleon',
            'Octopus',
            'Polar bear',
            'Raccoon',
            'Ringo Starr',
            'Salmon',
            'Sushi',
            'The Mona Lisa',
            'The North Pole',
            'The Titanic',
            'The White House',
            'Thomas Edison',
            'Walrus',
            'Warthog',
            'Wildebeest',
            'Yellowstone National Park',
        ],
    ),
    'nouns': WordList(
        short_name='Nouns',
        description='All nouns all the time.',
        hard=[
            'airplane',
            'airport',
            'animal',
            'arithmetic',
            'balloon',
            'banana',
            'baseball',
            'basket',
            'basketball',
            'bedroom',
            'breakfast',
            'building',
            'butter',
            'button',
            'cabbage',
            'calculator',
            'cattle',
            'celery',
            'cellar',
            'cemetery',
            'cheese',
            'cherry',
            'chicken',
            'clock',
            'copper',
            'crayon',
            'curtain',
            'cushion',
            'daughter',
            'doctor',
            'donkey',
            'earthquake',
            'eggnog',
            'engine',
            'feather',
            'finger',
            'giraffe',
            'goldfish',
            'guitar',
            'hammer',
            'icicle',
            'island',
            'jellyfish',
            'kettle',
            'kitten',
            'ladybug',
            'leather',
            'lettuce',
            'library',
            'mailbox',
            'marble',
            'monkey',
            'mountain',
            'notebook',
            'oatmeal',
            'orange',
            'pancake',
            'pencil',
            'pickle',
            'pizza',
            'playground',
            'popcorn',
            'potato',
            'quarter',
            'quartz',
            'rabbit',
            'rain',
            'receipt',
            'scarecrow',
            'school',
            'scissors',
            'sidewalk',
            'snail',
            'snake',
            'sneeze',
            'spider',
            'sponge',
            'square',
            'squirrel',
            'stick',
            'stocking',
            'stomach',
            'stream',
            'street',
            'stretch',
            'string',
            'sweater',
            'thread',
            'throat',
            'throne',
            'thunder',
            'ticket',
            'tomato',
            'toothbrush',
            'trouble',
            'trousers',
            'truck',
            'turkey',
            'umbrella',
            'volleyball',
            'window',
            'Yak-shaving',
        ],
        easy=[
            'air',
            'alarm',
            'ant',
            'apple',
            'arm',
            'art',
            'baby',
            'back',
            'bag',
            'ball',
            'band',
            'bat',
            'bath',
            'bean',
            'bear',
            'bed',
            'bee',
            'beef',
            'bell',
            'berry',
            'bike',
            'bird',
            'birth',
            'bite',
            'blade',
            'blood',
            'blow',
            'board',
            'boat',
            'body',
            'bomb',
            'bone',
            'book',
            'boot',
            'box',
            'boy',
            'brain',
            'brake',
            'brass',
            'bread',
            'brick',
            'brush',
            'bun',
            'cake',
            'camp',
            'can',
            'car',
            'card',
            'care',
            'cart',
            'cat',
            'cause',
            'cave',
            'chain',
            'chair',
            'chalk',
            'chess',
            'chin',
            'clam',
            'class',
            'cloth',
            'club',
            'coal',
            'coast',
            'coat',
            'coil',
            'color',
            'comb',
            'cook',
            'copy',
            'cord',
            'cork',
            'corn',
            'cough',
            'cover',
            'cow',
            'crack',
            'crate',
            'cream',
            'crib',
            'crime',
            'crook',
            'crow',
            'crowd',
            'crown',
            'crush',
            'cry',
            'cub',
            'cup',
            'curve',
            'dad',
            'day',
            'death',
            'debt',
            'deer',
            'desk',
            'dime',
            'dirt',
            'dock',
            'dog',
            'dogs',
            'doll',
            'dolls',
            'door',
            'drain',
            'dress',
            'drink',
            'drop',
            'drug',
            'drum',
            'dust',
            'ear',
            'earth',
            'edge',
            'elbow',
            'end',
            'error',
            'event',
            'eyes',
            'face',
            'fact',
            'fall',
            'fan',
            'fang',
            'farm',
            'fear',
            'feast',
            'feet',
            'field',
            'fifth',
            'fight',
            'fire',
            'fish',
            'flag',
            'flame',
            'flesh',
            'flock',
            'floor',
            'fly',
            'fog',
            'fold',
            'food',
            'foot',
            'force',
            'fork',
            'form',
            'fowl',
            'frame',
            'frog',
            'front',
            'fruit',
            'fuel',
            'game',
            'gate',
            'geese',
            'ghost',
            'glass',
            'glove',
            'glue',
            'goat',
            'gold',
            'goose',
            'grade',
            'grain',
            'grape',
            'grass',
            'grip',
            'group',
            'guide',
            'gun',
            'hair',
            'hall',
            'hat',
            'hate',
            'head',
            'heart',
            'heat',
            'help',
            'hen',
            'hill',
            'hole',
            'home',
            'honey',
            'hook',
            'hope',
            'horn',
            'horse',
            'hose',
            'hot',
            'hour',
            'house',
            'humor',
            'ice',
            'idea',
            'ink',
            'iron',
            'jail',
            'jam',
            'jar',
            'jeans',
            'jelly',
            'jewel',
            'join',
            'joke',
            'judge',
            'juice',
            'jump',
            'key',
            'kick',
            'kiss',
            'kite',
            'kitty',
            'knee',
            'knife',
            'knot',
            'lace',
            'lake',
            'lamp',
            'land',
            'laugh',
            'lead',
            'leaf',
            'leg',
            'level',
            'lift',
            'light',
            'limit',
            'line',
            'linen',
            'lip',
            'list',
            'loaf',
            'lock',
            'look',
            'loss',
            'love',
            'low',
            'lunch',
            'magic',
            'maid',
            'man',
            'map',
            'mark',
            'mask',
            'mass',
            'match',
            'meal',
            'meat',
            'men',
            'metal',
            'mice',
            'milk',
            'mind',
            'mine',
            'mint',
            'mist',
            'mom',
            'money',
            'month',
            'moon',
            'mouth',
            'move',
            'music',
            'nail',
            'name',
            'neck',
            'need',
            'nerve',
            'nest',
            'net',
            'news',
            'night',
            'noise',
            'north',
            'nose',
            'note',
            'nut',
            'ocean',
            'offer',
            'oil',
            'order',
            'oven',
            'owl',
            'owner',
            'page',
            'pail',
            'pain',
            'paint',
            'pan',
            'paper',
            'park',
            'part',
            'party',
            'paste',
            'patch',
            'peace',
            'pear',
            'pen',
            'pest',
            'pet',
            'pie',
            'pig',
            'pin',
            'pipe',
            'place',
            'plane',
            'plant',
            'plate',
            'play',
            'plot',
            'point',
            'pot',
            'power',
            'price',
            'print',
            'prose',
            'pull',
            'pump',
            'push',
            'queen',
            'quiet',
            'quill',
            'quilt',
            'rail',
            'rain',
            'rake',
            'range',
            'rat',
            'rate',
            'ray',
            'rest',
            'rice',
            'rifle',
            'ring',
            'river',
            'road',
            'robin',
            'rock',
            'rod',
            'roll',
            'roof',
            'room',
            'root',
            'rose',
            'route',
            'rub',
            'rule',
            'run',
            'sack',
            'sail',
            'salt',
            'sand',
            'scale',
            'scarf',
            'scene',
            'scent',
            'screw',
            'sea',
            'seat',
            'seed',
            'self',
            'sense',
            'shade',
            'shake',
            'shame',
            'shape',
            'sheep',
            'sheet',
            'shelf',
            'ship',
            'shirt',
            'shock',
            'shoe',
            'shoes',
            'shop',
            'show',
            'side',
            'sign',
            'silk',
            'sink',
            'size',
            'skate',
            'skin',
            'skirt',
            'sky',
            'slave',
            'sleep',
            'sleet',
            'slip',
            'slope',
            'smash',
            'smell',
            'smile',
            'smoke',
            'snail',
            'snake',
            'snow',
            'soap',
            'sock',
            'soda',
            'sofa',
            'son',
            'song',
            'sort',
            'sound',
            'soup',
            'space',
            'spade',
            'spark',
            'spoon',
            'spot',
            'spy',
            'stage',
            'stamp',
            'star',
            'start',
            'steam',
            'steel',
            'stem',
            'step',
            'stew',
            'stick',
            'stone',
            'stop',
            'store',
            'story',
            'stove',
            'straw',
            'sugar',
            'suit',
            'sun',
            'swim',
            'swing',
            'table',
            'tail',
            'talk',
            'tank',
            'taste',
            'tax',
            'team',
            'teeth',
            'tent',
            'test',
            'thing',
            'thumb',
            'tiger',
            'time',
            'tin',
            'title',
            'toad',
            'toe',
            'tooth',
            'top',
            'touch',
            'town',
            'toy',
            'trade',
            'trail',
            'train',
            'tray',
            'tree',
            'trick',
            'trip',
            'truck',
            'tub',
            'turn',
            'twig',
            'twist',
            'uncle',
            'unit',
            'use',
            'value',
            'van',
            'vase',
            'veil',
            'vein',
            'verse',
            'vest',
            'view',
            'voice',
            'walk',
            'wall',
            'war',
            'wash',
            'waste',
            'watch',
            'water',
            'wave',
            'wax',
            'way',
            'week',
            'wheel',
            'whip',
            'wind',
            'wine',
            'wing',
            'wire',
            'wish',
            'woman',
            'women',
            'wool',
            'worm',
            'wound',
            'wrist',
        ],
    ),
    'space': WordList(
        short_name='Space',
        description='Space-related words',
        easy=[
            'Apollo',
            'Moon',
            'Sun',
            'Venus',
            'Pluto',
            'Mars',
            'Earth',
            'Mercury',
            'Jupiter',
            'Saturn',
            'Uranus',
            'Neptune',
            'Planet',
            'Space',
            'Star'
        ],
        medium=[
            'Alpha Centauri',
            'Asteroid',
            'Astronaut',
            'Astronomy',
            'Big Bang Theory',
            'Black Hole',
            'Buzz Aldrin',
            'Ceres',
            'Comet',
            'Constellation',
            'Cosmonaut',
            'Crater',
            'Curiosity Rover',
            'Eclipse',
            'Event Horizon',
            'Galaxy',
            'Gas Giant',
            'Gravity',
            'Hubble Telescope',
            'International Space Station',
            'Laika (First dog in space)',
            'Lightyear',
            'Meteor',
            'Milky Way',
            'Mercury',
            'NASA',
            'Nebula',
            'Neil Armstrong',
            'Orbit',
            'Parsec',
            'Pulsar',
            'Quasar',
            'Red Dwarf',
            'Red Giant',
            'Red Shift',
            'Rocket',
            'Satellite',
            'Solar Flare',
            'Solar System',
            'Sputnik',
            'Supernova',
            'Telescope',
            'Titan',
            'Universe',
            'White Dwarf',
            'Wormhole',
            'Yellow Dwarf',
            'Vacuum'
        ]),
    'extended': WordList(
        short_name='extended',
        description='Auto-generated Word List',
        easy=[
            'actor',
            'adult',
            'airplane',
            'alive',
            'ankle',
            'apple',
            'awake',
            'baby',
            'backpack',
            'bald',
            'balloon',
            'banana',
            'bark',
            'baseball',
            'basketball',
            'bat',
            'bathroom',
            'beach',
            'beak',
            'bed',
            'bedtime',
            'below',
            'bench',
            'big',
            'black',
            'blanket',
            'blind',
            'blue jeans',
            'boat',
            'book',
            'bounce',
            'bowl',
            'boy',
            'bracelet',
            'brake',
            'branch',
            'broccoli',
            'broken',
            'broom',
            'brother',
            'bug',
            'bumblebee',
            'butterfly',
            'button',
            'buy',
            'calculator',
            'camera',
            'car',
            'chair',
            'cheek',
            'chocolate',
            'Christmas',
            'circle',
            'city',
            'clap',
            'classroom',
            'clean',
            'cold',
            'comb',
            'corn',
            'count',
            'cousin',
            'crack',
            'crib',
            'cube',
            'cup',
            'cupcake',
            'curl',
            'dad',
            'dance',
            'deep',
            'diamond',
            'dirt',
            'dog',
            'door',
            'dream',
            'drum',
            'duck',
            'egg',
            'elephant',
            'envelope',
            'exercise',
            'fact',
            'fall',
            'family',
            'farm',
            'feet',
            'fire',
            'first',
            'fish',
            'flashlight',
            'flower',
            'fly',
            'football',
            'forehead',
            'fork',
            'fountain',
            'frown',
            'frying pan',
            'full',
            'fur',
            'gift',
            'giraffe',
            'glasses',
            'grape',
            'gum',
            'gym',
            'hair',
            'half',
            'hamburger',
            'hand',
            'happy',
            'heavy',
            'helicopter',
            'help',
            'hit',
            'homework',
            'hook',
            'horse',
            'hotel',
            'house',
            'ice cream cone',
            'Internet',
            'iron',
            'jacket',
            'jail',
            'jar',
            'jellyfish',
            'juice',
            'king',
            'kite',
            'lamp',
            'leaf',
            'legs',
            'lightning',
            'line',
            'lion',
            'lizard',
            'long',
            'loud',
            'love',
            'low',
            'lunchbox',
            'lung',
            'mailbox',
            'mailman',
            'MC Hammer',
            'melt',
            'Mickey Mouse',
            'milk',
            'mitten',
            'moo',
            'moon',
            'mouth',
            'music',
            'nail polish',
            'neighbor',
            'nest',
            'nice',
            'notebook',
            'old',
            'owl',
            'pantry',
            'party',
            'pencil',
            'person',
            'picture',
            'pillow',
            'play',
            'policeman',
            'popsicle',
            'purple',
            'purse',
            'quiet',
            'rainbow',
            'ranch',
            'refrigerator',
            'restaurant',
            'rhyme',
            'ride',
            'river',
            'road',
            'rock',
            'rocket',
            'roof',
            'room',
            'run',
            'school bus',
            'scientist',
            'sea turtle',
            'sea',
            'seashell',
            'share',
            'shark',
            'ship',
            'shoe',
            'shopping',
            'shower',
            'sink',
            'Sir Mix-A-Lot',
            'skateboard',
            'sleep',
            'snail',
            'snake',
            'soap',
            'sock',
            'square',
            'stamp',
            'stapler',
            'star',
            'stick',
            'stomach',
            'stream',
            'street',
            'study',
            'suitcase',
            'sun',
            'swimming pool',
            'swing',
            'table',
            'tail',
            'tent',
            'thunder',
            'tissue',
            'touchdown',
            'towel',
            'tractor',
            'train',
            'trip',
            'truck',
            'turtle',
            'umbrella',
            'watch',
            'wrinkle',
            'yo-yo',
            'zero',
        ],
        medium=[
            'atmosphere',
            'attic',
            'bobsled',
            'bunk bed',
            'button',
            'cabinet',
            'candlestick',
            'cookie',
            'crumb',
            'dump',
            'elf',
            'engineer',
            'estate',
            'family reunion',
            'funeral',
            'garage',
            'gasoline',
            'goblin',
            'gold',
            'gumball',
            'hug',
            'human',
            'ironing board',
            'kid',
            'lip',
            'map',
            'mud',
            'Nirvana',
            'oak tree',
            'park',
            'pharmacy',
            'ping pong',
            'quicksand',
            'ribbon',
            'spaceship',
            'spy',
            'tulip',
            'virus',
            'yolk',
            'youth',
            'yoyo',
            'zebra',
            'zinc',
            'zipper',
            'zombie',
            'zucchini',
        ],
        hard=[
            'abrasive',
            'ballpoint pen',
            'banana peel',
            'battle',
            'bay',
            'bedbug',
            'beehive',
            'bellhop',
            'blimp',
            'bucket',
            'campsite',
            'chain',
            'clay',
            'cloak',
            'coast',
            'crows nest',
            'diver',
            'hatch',
            'highway',
            'humidifier',
            'apprentice',
            'laundry basket',
            'lollipop',
            'mascot',
            "Murphys Law",
            'nanny',
            'potassium',
            'race',
            'radiator',
            'sheriff',
            'Moe Shop',
        ]),
    'movies': WordList(
        short_name='Movies',
        description='Movies',
        medium=[
            "12 Angry Men",
            "2001: A Space Odyssey",
            "A Beautiful Mind",
            "A Clockwork Orange",
            "Aladdin",
            "Aliens",
            "Amadeus",
            "American History X",
            "Apocalypse Now",
            "Avengers: Infinity War",
            "Back to the Future",
            "Batman Begins",
            "Before Sunrise",
            "Blade Runner",
            "Braveheart",
            "Casablanca",
            "Catch Me If You Can",
            "Citizen Kane",
            "Dead Poets Society",
            "Die Hard",
            "Django Unchained",
            "Eternal Sunshine of the Spotless Mind",
            "Fargo",
            "Fight Club",
            "Finding Nemo",
            "Forrest Gump",
            "Full Metal Jacket",
            "Gladiator",
            "Gone Girl",
            "Good Will Hunting",
            "Gran Torino",
            "Groundhog Day",
            "How to Train Your Dragon",
            "Howls Moving Castle",
            "Inception",
            "Indiana Jones and the Raiders of the Lost Ark",
            "Inglourious Basterds",
            "Inside Out",
            "Interstellar",
            "Its a Wonderful Life",
            "Jaws",
            "Joker",
            "Judgment at Nuremberg",
            "Jurassic Park",
            "Kill Bill: Vol. 1",
            "Léon: The Professional",
            "Life of Brian",
            "Mad Max: Fury Road",
            "Memento",
            "Monsters, Inc.",
            "Monty Python and the Holy Grail",
            "My Neighbor Totoro",
            "No Country for Old Men",
            "One Flew Over the Cuckoos Nest",
            "Pans Labyrinth",
            "Pirates of the Caribbean: The Curse of the Black Pearl",
            "Platoon",
            "Princess Mononoke",
            "Psycho",
            "Pulp Fiction",
            "Raging Bull",
            "Ratatouille",
            "Requiem for a Dream",
            "Reservoir Dogs",
            "Rocky",
            "Saving Private Ryan",
            "Scarface",
            "Schindlers List",
            "Shutter Island",
            "Spider-Man: Into the Spider-Verse",
            "Spirited Away",
            "Stand by Me",
            "Star Wars",
            "Taxi Driver",
            "Terminator 2: Judgment Day",
            "The Apartment",
            "The Big Lebowski",
            "The Dark Knight",
            "The Departed",
            "The Green Mile",
            "The Hunt",
            "The Incredibles",
            "The Iron Giant",
            "The Lion King",
            "The Lord of the Rings: The Fellowship of the Ring",
            "The Matrix",
            "The Pianist",
            "The Prestige",
            "The Shawshank Redemption",
            "The Shining",
            "The Silence of the Lambs",
            "The Sixth Sense",
            "The Sound of Music",
            "The Terminator",
            "The Usual Suspects",
            "The Wizard of Oz",
            "There Will Be Blood",
            "To Kill a Mockingbird",
            "Top Gun: Maverick",
            "Toy Story",
            "Trainspotting",
            "V for Vendetta",
            "WALL·E",
        ]),
    'movie_characters': WordList(
        short_name='Movie Characters',
        description='Character names from Movies',
        medium=[
            'Ace Ventura',
            'Agent Smith',
            'Aladdin',
            'Aragorn',
            'Bambi',
            'Bane',
            'Batman',
            'BeetleJuice',
            'Bilbo Baggins',
            'Boba Fett',
            'Buzz Lightyear',
            'Captain America',
            'Captain Hook',
            'Captain Jack Sparrow',
            'Captain Kirk',
            'Casper',
            'Catwoman',
            'Cheshire Cat',
            'Cinderella',
            'Cleopatra',
            'Conan the Barbarian',
            'Darth Maul',
            'Darth Vader',
            'Doc Brown',
            'Doc Holiday',
            'Donald Duck',
            'Dopey',
            'Dracula',
            'Dumbo',
            'E.T.',
            'Ebenezer Scrooge',
            'Edward Scissor Hands',
            'Freddy Krueger',
            'Frodo',
            'Galadriel',
            'Gandalf ',
            'Godzilla',
            'Gollum',
            'Goofy',
            'Groot',
            'Han Solo',
            'Harley Quinn',
            'Harry Potter',
            'Indiana Jones',
            'Inigo Montoya',
            'Iron Man',
            'Jabba the Hutt',
            'Jack and the Beanstalk',
            'Jack Skellington',
            'James Bond',
            'John McClane',
            'Rambo',
            'John Wick',
            'Joker',
            'Lara Croft',
            'Legolas',
            'Luke Skywalker',
            'Mad Max',
            'Magic Carpet',
            'Mufasa',
            'Mulan',
            'Neo',
            'Obi-Wan Kenobi',
            'Optimus Prime',
            'Palpatine',
            'Peter Pan',
            'Pikachu',
            'Pinocchio',
            'Pocahontas',
            'Popeye',
            'Rapunzel',
            'Robin Hood',
            'Robocop',
            'Roger Rabbit',
            'Sheriff Woody',
            'Sherlock Holmes',
            'Spider-Man',
            'Spock',
            'Superman',
            'Sweeney Todd',
            'Tarzan',
            'Terminator',
            'Thanos',
            'The Hulk',
            'The Mad Hatter',
            'Thor',
            'Vito Corleone',
            'Wednesday Addams',
            'Willy Wonka',
            'Wolverine',
            'Wonder Woman',
            'Wyatt Earp',
            'Yoda',
            'Zeus',
            'Zorro',
        ]),
    'video_games': WordList(
        short_name='Video Game Characters',
        description='Characters from Video Games',
        medium=[
            'Mario',
            'Luigi',
            'Princess Peach',
            'Triss Merigold (The Witcher)',
            'Geralt of Rivia (The Witcher)',
            'Aloy (Horizon: Zero Dawn)',
            'Albedo (Genshin Impact)',
            'Amber (Genshin Impact)',
            'Barbara (Genshin Impact)',
            'Bennett (Genshin Impact)',
            'Diluc (Genshin Impact)',
            'Diona (Genshin Impact)',
            'Eula (Genshin Impact)',
            'Fischl (Genshin Impact)',
            'Jean (Genshin Impact)',
            'Kaeya (Genshin Impact)',
            'Klee (Genshin Impact)',
            'Lisa (Genshin Impact)',
            'Mika (Genshin Impact)',
            'Mona (Genshin Impact)',
            'Noelle (Genshin Impact)',
            'Razor (Genshin Impact)',
            'Rosaria (Genshin Impact)',
            'Sucrose (Genshin Impact)',
            'Venti (Genshin Impact)',
            'Solid Snake',
        ]),
    'actors': WordList(
        short_name='Actors/Actresses',
        description='Actors and Actresses from Movies',
        medium=[
            'Chris Evans',
            'Robert Downey Jr.',
            'Jennifer Lawrence',
            'Channing Tatum',
            'George Clooney',
            'Johnny Depp',
            'Margot Robbie',
            'Ryan Reynolds',
            'Scarlett Johansson',
            'Brad Pitt',
            'Matt Damon',
            'Will Smith',
            'Ben Affleck',
            'Matthew McConaughey',
            'Chris Hemsworth',
            'Dwayne (The Rock) Johnson',
            'Tom Hiddleston',
            'Jamie Foxx',
            'Nicolas Cage',
            'Tom Cruise',
            'Chris Pratt',
            'Samuel L. Jackson',
            'Leonardo DiCaprio',
            'Tyler Perry',
            'Gal Gadot',
            'Tom Hanks',
            'Will Ferrell',
            'Ben Stiller',
            'Melissa McCarthy',
            'Vin Diesel',
            'Charlize Theron',
            'Anna Kendrick',
            'Denzel Washington',
        ]),
    'games': WordList(
        short_name='Board and Video Games',
        description='Board and Video Games',
        medium=[
            'Animal Crossing: New Horizons',
            'Baldurs Gate 3',
            'Batman: Arkham City',
            'BioShock Infinite',
            'BioShock',
            'Borderlands 2',
            'Call of Duty 4: Modern Warfare',
            'Celeste',
            'Chrono Cross',
            'Devil May Cry',
            'Diablo III',
            'Disco Elysium',
            'Duck Hunt',
            'Elden Ring',
            'Final Fantasy',
            'Gears of War',
            'God of War',
            'GoldenEye 007',
            'Gran Turismo',
            'Grand Theft Auto V',
            'Half-Life 2',
            'Halo: Combat Evolved',
            'Human: Fall Flat',
            'LittleBigPlanet',
            'Mario Kart 8 / Deluxe',
            'Mass Effect 2',
            'Metal Gear Solid V: The Phantom Pain',
            'Metroid Prime',
            'Minecraft',
            'Nintendogs',
            'Overwatch',
            'Pac-Man',
            'Perfect Dark',
            'Persona 5 Royal',
            'Pokémon',
            'Portal 2',
            'PUBG: Battlegrounds',
            'Quake',
            'Red Dead Redemption',
            'Resident Evil 4',
            'Sid Meiers Civilization II',
            'Sonic the Hedgehog',
            'SoulCalibur',
            'Super Mario Bros. 3',
            'Super Mario Galaxy',
            'Super Mario Odyssey',
            'Super Mario World',
            'Super Smash Bros. Ultimate',
            'Tekken 3',
            'Terraria',
            'Tetris',
            'The Elder Scrolls V: Skyrim',
            'The Last of Us',
            'The Legend of Zelda: A Link to the Past',
            'The Legend of Zelda: Breath of the Wild',
            'The Orange Box',
            'The Walking Dead',
            'The Witcher 3: Wild Hunt',
            'Tony Hawks Pro Skater 2',
            'Uncharted 2: Among Thieves',
            'Wii Sports',
            'World of Goo',
        ]),
}
